# .github/workflows/ci.yml
name: Pipeline de CI - Backend e Frontend

# Gatilhos: roda em todo push ou pull request para a branch main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job para testar o backend
  test-backend:
    runs-on: ubuntu-latest # Roda numa máquina virtual Linux
    defaults:
      run:
        working-directory: ./agendamento-api # Define o diretório de trabalho
    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v3

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 3. Instalar dependências
        run: npm install

      - name: 4. Rodar testes de unidade
        run: npm test

  # Job para analisar o frontend
  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # Define o diretório de trabalho
    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v3

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 3. Instalar dependências
        run: npm install

      - name: 4. Rodar análise estática (lint)
        run: npm run lint